spring:
  datasource:
    url: jdbc:h2:C:/Users/Administrator/IntelijProjects/ss/mybatis/data/testdb;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update